function final_stop_devoicing(word){
	let final_features = deepcopy(CONSONANTS[word.slice(-1)[0]]);
	if(final_features["voice"]!=true){
		console.log('voicelss');
		return word;
	}else{
		final_features["voice"] = false;
		for(c in CONSONANTS){
			var features = CONSONANTS[c];
			if(check_features(final_features, features)){
				return word.slice(0, word.length-1) + c;
			}
		}
		return word;
	}
}

function check_features(feat1, feat2){
	return JSON.stringify(feat1) == JSON.stringify(feat2);
}

function deepcopy(obj){
  return JSON.parse(JSON.stringify(obj));
}

const CONSONANTS = {
  "p":{
		"syllabic": false,
		"consonantal": true,
		"sonorant": false,
		"nasal": false,
		"anterior": true,
		"coronal": false,
		"high": false,
		"back": false,
		"continuant": false,
		"sibilant": false,
		"voice": false,
		"lateral": false,
		"aspiration": false
	},
	"P":{
		"syllabic": false,
		"consonantal": true,
		"sonorant": false,
		"nasal": false,
		"anterior": true,
		"coronal": false,
		"high": false,
		"back": false,
		"continuant": false,
		"sibilant": false,
		"voice": false,
		"lateral": false,
		"aspiration": true
  },
	"b": {
		"syllabic": false,
		"consonantal": true,
		"sonorant": false,
		"nasal": false,
		"anterior": true,
		"coronal": false,
		"high": false,
		"back": false,
		"continuant": false,
		"sibilant": false,
		"voice": true,
		"lateral": false,
		"aspiration": false
  },
  "m": {
		"syllabic": false,
		"consonantal": true,
		"sonorant": true,
		"nasal": true,
		"anterior": true,
		"coronal": false,
		"high": false,
		"back": false,
		"continuant": false,
		"sibilant": false,
		"voice": true,
		"lateral": false,
		"aspiration": false
    },
  "t": {
		"syllabic": false,
		"consonantal": true,
		"sonorant": false,
		"nasal": false,
		"anterior": true,
		"coronal": true,
		"high": false,
		"back": false,
		"continuant": false,
		"sibilant": false,
		"voice": false,
		"lateral": false,
		"aspiration": false
	},
	"T": {
		"syllabic": false,
		"consonantal": true,
		"sonorant": false,
		"nasal": false,
		"anterior": true,
		"coronal": true,
		"high": false,
		"back": false,
		"continuant": false,
		"sibilant": false,
		"voice": false,
		"lateral": false,
		"aspiration": true
  },
  "d": {
		"syllabic": false,
		"consonantal": true,
		"sonorant": false,
		"nasal": false,
		"anterior": true,
		"coronal": true,
		"high": false,
		"back": false,
		"continuant": false,
		"sibilant": false,
		"voice": true,
		"lateral": false,
		"aspiration": false
  },
	"n": {
		"syllabic": false,
		"consonantal": true,
		"sonorant": true,
		"nasal": true,
		"anterior": true,
		"coronal": true,
		"high": false,
		"back": false,
		"continuant": false,
		"sibilant": false,
		"voice": true,
		"lateral": false,
		"aspiration": false
	},
	"k": {
		"syllabic": false,
		"consonantal": true,
		"sonorant": false,
		"nasal": false,
		"anterior": false,
		"coronal": false,
		"high": true,
		"back": true,
		"continuant": false,
		"sibilant": false,
		"voice": false,
		"lateral": false,
		"aspiration": false
	},
	"K": {
		"syllabic": false,
		"consonantal": true,
		"sonorant": false,
		"nasal": false,
		"anterior": false,
		"coronal": false,
		"high": true,
		"back": true,
		"continuant": false,
		"sibilant": false,
		"voice": false,
		"lateral": false,
		"aspiration": true
	},
  "g": {
		"syllabic": false,
		"consonantal": true,
		"sonorant": false,
		"nasal": false,
		"anterior": false,
		"coronal": false,
		"high": true,
		"back": true,
		"continuant": false,
		"sibilant": false,
		"voice": true,
		"lateral": false,
		"aspiration": false,
  },
  "ŋ": {
		"syllabic": false,
		"consonantal": true,
		"sonorant": true,
		"nasal": true,
		"anterior": false,
		"coronal": false,
		"high": true,
		"back": true,
		"continuant": false,
		"sibilant": false,
		"voice": true,
		"lateral": false,
		"aspiration": false
	},
  "f": {
		"syllabic": false,
		"consonantal": true,
		"sonorant": false,
		"nasal": false,
		"anterior": true,
		"coronal": false,
		"high": false,
		"back": false,
		"continuant": true,
		"sibilant": false,
		"voice": false,
		"lateral": false,
		"aspiration": false
  },
	"v": {
		"syllabic": false,
		"consonantal": true,
		"sonorant": false,
		"nasal": false,
		"anterior": true,
		"coronal": false,
		"high": false,
		"back": false,
		"continuant": true,
		"sibilant": false,
		"voice": true,
		"lateral": false,
		"aspiration": false
    },
  "s": {
		"syllabic": false,
		"consonantal": true,
		"sonorant": false,
		"nasal": false,
		"anterior": true,
		"coronal": true,
		"high": false,
		"back": false,
		"continuant": true,
		"sibilant": true,
		"voice": false,
		"lateral": false,
		"aspiration": false
  },
  "z": {
		"syllabic": false,
		"consonantal": true,
		"sonorant": false,
		"nasal": false,
		"anterior": true,
		"coronal": true,
		"high": false,
		"back": false,
		"continuant": true,
		"sibilant": true,
		"voice": true,
		"lateral": false,
		"aspiration": false
    },
	"θ": {
		"syllabic": false,
		"consonantal": true,
		"sonorant": false,
		"nasal": false,
		"anterior": true,
		"coronal": true,
		"high": false,
		"back": false,
		"continuant": true,
		"sibilant": false,
		"voice": false,
		"lateral": false,
		"aspiration": false
  },
  "ð": {
		"syllabic": false,
		"consonantal": true,
		"sonorant": false,
		"nasal": false,
		"anterior": true,
		"coronal": true,
		"high": false,
		"back": false,
		"continuant": true,
		"sibilant": false,
		"voice": true,
		"lateral": false,
		"aspiration": false
  },
  "ʃ": {
		"syllabic": false,
		"consonantal": true,
		"sonorant": false,
		"nasal": false,
		"anterior": false,
		"coronal": true,
		"high": false,
		"back": false,
		"continuant": true,
		"sibilant": true,
		"voice": false,
		"lateral": false,
		"aspiration": false
  },
	"ʒ": {
		"syllabic": false,
		"consonantal": true,
		"sonorant": false,
		"nasal": false,
		"anterior": false,
		"coronal": true,
		"high": false,
		"back": false,
		"continuant": true,
		"sibilant": true,
		"voice": true,
		"lateral": false,
		"aspiration": false
	},
  "ʧ": {
		"syllabic": false,
		"consonantal": true,
		"sonorant": false,
		"nasal": false,
		"anterior": false,
		"coronal": true,
		"high": false,
		"back": false,
		"continuant": false,
		"sibilant": true,
		"voice": false,
		"lateral": false,
		"aspiration": false
  },
	"ʤ": {
		"syllabic": false,
		"consonantal": true,
		"sonorant": false,
		"nasal": false,
		"anterior": false,
		"coronal": true,
		"high": false,
		"back": false,
		"continuant": false,
		"sibilant": true,
		"voice": true,
		"lateral": false,
		"aspiration": false
	},
    "l": {
        "syllabic": false,
        "consonantal": true,
        "sonorant": true,
        "nasal": false,
        "anterior": true,
        "coronal": true,
        "high": false,
        "back": false,
        "continuant": true,
        "sibilant": false,
        "voice": true,
        "lateral": true
    },
    "r": {
        "syllabic": false,
        "consonantal": true,
        "sonorant": true,
        "nasal": false,
        "anterior": true,
        "coronal": true,
        "high": false,
        "back": false,
        "continuant": true,
        "sibilant": false,
        "voice": true,
        "lateral": false
    },
    "y": {
        "syllabic": false,
        "consonantal": false,
        "sonorant": true,
        "nasal": false,
        "anterior": false,
        "coronal": false,
        "high": true,
        "back": false,
        "continuant": true,
        "sibilant": false,
        "voice": true,
        "lateral": false
    },
    "w": {
        "syllabic": false,
        "consonantal": false,
        "sonorant": true,
        "nasal": false,
        "anterior": false,
        "coronal": false,
        "high": true,
        "back": true,
        "continuant": true,
        "sibilant": false,
        "voice": true,
        "lateral": false
    },
    "h": {
        "syllabic": false,
        "consonantal": false,
        "sonorant": false,
        "nasal": false,
        "anterior": false,
        "coronal": false,
        "high": false,
        "back": false,
        "continuant": true,
        "sibilant": false,
        "voice": false,
        "lateral": false
    },
    "ʔ": {
        "syllabic": false,
        "consonantal": false,
        "sonorant": false,
        "nasal": false,
        "anterior": false,
        "coronal": false,
        "high": false,
        "back": false,
        "continuant": false,
        "sibilant": false,
        "voice": false,
        "lateral": false
    }
}